[project]
name = "python-web-demo"
version = "0.1.0"
description = "Demo of a Python web using flask, flask_cors and html "
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "flask-cors>=6.0.1",
]
